server:
  port: 9090

spring:

  application:
    name: smart-finance-api-customer

  flyway:
    validate-on-migrate: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: false
