logging:
  level:
    org.hibernate: INFO
    org.flywaydb: DEBUG
    com.smartfinance.finance: DEBUG
    org.springframework.security: TRACE

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: sf-user
    password: P@ssw0rd

# Web Clients
client:

  currency:
    host: http://localhost:9090
    auth:
      user: spring
      password: secret

  customer:
    host: http://localhost:9092
    auth:
      user: spring
      password: secret